/**
 * SmartTemplateView - hlavní UI komponenta pro Smart Template mód
 */

import React, { useState, useEffect } from 'react';
import { Report, Audit, AuditStructure } from '../../types';
import { ReportDocument } from '../../types/smartReport';
import { SmartTemplateSelector } from './SmartTemplateSelector';
import { SmartReportDesigner } from './SmartReportDesigner';
import { SmartReportActions } from './SmartReportActions';
import { applySmartTemplate } from '../../services/smartTemplate/SmartTemplateEngine';
import { loadTemplate } from '../../services/smartTemplate/templateLoader';
import { saveSmartDraft, loadSmartDraft, saveSmartFinalVersion, listSmartFinalVersions, loadSmartFinalVersion } from '../../services/smartTemplate/reportDocumentService';
import { updateReportSmartMetadata } from '../../services/firestore/reports';
import { toast } from '../../utils/toast';
import { BackButton } from '../BackButton';

interface SmartTemplateViewProps {
  report: Report;
  audit: Audit;
  auditStructure: AuditStructure;
  onBack: () => void;
}

export const SmartTemplateView: React.FC<SmartTemplateViewProps> = ({
  report,
  audit,
  auditStructure,
  onBack
}) => {
  const [selectedTemplateId, setSelectedTemplateId] = useState<string>(report.smart?.selectedTemplateId || '');
  const [selectedVersion, setSelectedVersion] = useState<string>(report.smart?.selectedTemplateVersion || '');
  const [currentDocument, setCurrentDocument] = useState<ReportDocument | null>(null);
  const [mode, setMode] = useState<'draft' | 'final'>('draft');
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false); // Flag pro prevenci dvojího generování
  const [finalVersions, setFinalVersions] = useState<Array<{
    versionId: string;
    createdAt: string;
    createdBy: string;
    createdByName?: string;
  }>>([]);

  useEffect(() => {
    loadFinalVersions();
    // Zkusit načíst draft pokud existuje
    if (report.smart?.lastSmartDraftPath) {
      loadDraft();
    }
  }, [report.id]);

  // Automatické vygenerování layoutu pokud existuje Legacy report a není žádný draft
  useEffect(() => {
    const autoGenerateIfNeeded = async () => {
      // Podmínky pro auto-generování:
      // 1. Měli bychom mít report data (Legacy report je hotový)
      // 2. Měli bychom mít vybranou šablonu
      // 3. Nesmí existovat žádný draft ani finální verze
      // 4. Nesmíme už jednou vygenerovat (prevent double generation)
      if (
        report.reportData &&
        selectedTemplateId &&
        !currentDocument &&
        finalVersions.length === 0 &&
        !hasAutoGenerated &&
        !report.smart?.lastSmartDraftPath
      ) {
        setHasAutoGenerated(true);
        console.log('[SmartTemplateView] Automatické vygenerování layoutu...');
        
        // Generovat přímo zde místo volání handleGenerate (aby se vyhnulo dependency issues)
        setIsGenerating(true);
        try {
          const templateRules = await loadTemplate(selectedTemplateId || 'haccp-default', selectedVersion);
          const document = applySmartTemplate(
            report.reportData,
            templateRules,
            audit,
            auditStructure,
            { auditorSnapshot: report.auditorSnapshot }
          );
          await saveSmartDraft(report.id, document);
          setCurrentDocument(document);
          setMode('draft');
          toast.success('Layout byl automaticky vygenerován');
        } catch (error) {
          console.error('[SmartTemplateView] Chyba při automatickém generování:', error);
          toast.error('Chyba při automatickém generování layoutu');
        } finally {
          setIsGenerating(false);
        }
      }
    };

    autoGenerateIfNeeded();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedTemplateId, report.reportData, currentDocument, finalVersions.length]);

  const loadFinalVersions = async () => {
    try {
      const versions = await listSmartFinalVersions(report.id);
      setFinalVersions(versions);
    } catch (error) {
      console.error('[SmartTemplateView] Chyba při načítání verzí:', error);
    }
  };

  const loadDraft = async () => {
    try {
      const draft = await loadSmartDraft(report.id);
      if (draft) {
        setCurrentDocument(draft);
        setMode('draft');
      }
    } catch (error) {
      console.error('[SmartTemplateView] Chyba při načítání draftu:', error);
    }
  };

  const handleTemplateSelect = async (templateId: string, version: string) => {
    setSelectedTemplateId(templateId);
    setSelectedVersion(version);
    
    // Aktualizovat metadata v reportu
    try {
      await updateReportSmartMetadata(report.id, {
        selectedTemplateId: templateId,
        selectedTemplateVersion: version
      });
    } catch (error) {
      console.error('[SmartTemplateView] Chyba při aktualizaci metadata:', error);
    }
  };

  const handleGenerate = async () => {
    if (!report.reportData) {
      toast.error('Report data nejsou k dispozici. Nejdřív musí být vygenerován Legacy report.');
      return;
    }

    setIsGenerating(true);
    try {
      // Načíst šablonu
      const templateRules = await loadTemplate(selectedTemplateId || 'haccp-default', selectedVersion);
      
      // Vygenerovat ReportDocument
      const document = applySmartTemplate(
        report.reportData,
        templateRules,
        audit,
        auditStructure,
        { auditorSnapshot: report.auditorSnapshot }
      );
      
      // Uložit jako draft
      await saveSmartDraft(report.id, document);
      
      setCurrentDocument(document);
      setMode('draft');
      
      toast.success('Layout úspěšně vygenerován');
    } catch (error) {
      console.error('[SmartTemplateView] Chyba při generování:', error);
      toast.error('Chyba při generování layoutu: ' + (error instanceof Error ? error.message : 'Neznámá chyba'));
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSaveAsFinal = async () => {
    if (!currentDocument) {
      toast.error('Není žádný dokument k uložení');
      return;
    }

    try {
      const versionId = await saveSmartFinalVersion(report.id, currentDocument);
      setMode('final');
      await loadFinalVersions();
      toast.success(`Finální verze ${versionId} byla uložena`);
    } catch (error) {
      console.error('[SmartTemplateView] Chyba při ukládání finální verze:', error);
      toast.error('Chyba při ukládání finální verze');
    }
  };

  const handleLoadFinalVersion = async (versionId: string) => {
    try {
      const document = await loadSmartFinalVersion(report.id, versionId);
      setCurrentDocument(document);
      setMode('final');
      toast.success('Finální verze načtena');
    } catch (error) {
      console.error('[SmartTemplateView] Chyba při načítání finální verze:', error);
      toast.error('Chyba při načítání finální verze');
    }
  };

  const handleDocumentUpdate = (document: ReportDocument) => {
    setCurrentDocument(document);
  };

  return (
    <div className="w-full space-y-6">
      {/* Header s tlačítkem zpět */}
      <div className="flex items-center justify-between print:hidden">
        <h3 className="text-2xl font-bold text-gray-900">Smart Template</h3>
        <BackButton onClick={onBack} label="Zpět" />
      </div>

      {/* Template Selector */}
      <SmartTemplateSelector
        selectedTemplateId={selectedTemplateId}
        selectedVersion={selectedVersion}
        onTemplateSelect={handleTemplateSelect}
        onGenerate={handleGenerate}
        isGenerating={isGenerating}
      />

      {/* Designer a Actions */}
      {currentDocument ? (
        <>
          <SmartReportDesigner
            document={currentDocument}
            onDocumentUpdate={handleDocumentUpdate}
          />
          <SmartReportActions
            report={report}
            document={currentDocument}
            mode={mode}
            finalVersions={finalVersions}
            onSaveAsFinal={handleSaveAsFinal}
            onLoadFinalVersion={handleLoadFinalVersion}
            onRegenerate={handleGenerate}
          />
        </>
      ) : (
        <div className="text-center p-12 bg-gray-50 rounded-lg">
          <p className="text-gray-600 mb-4">Vyberte šablonu a klikněte na "Vygenerovat layout" pro vytvoření návrhu.</p>
        </div>
      )}
    </div>
  );
};

export default SmartTemplateView;

